# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bioviz
channels:
  - conda-forge
dependencies:
  - biorbd >=1.9.5
  - matplotlib
  - pyomeca
  - ezc3d
  - vtk
  - pyqt
  - packaging
  - setuptools
