# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bioptim
channels:
  - conda-forge
dependencies:
  - biorbd >=1.6.1
  - python >=3.9
  - numpy
  - matplotlib
  - scipy
  - pyomeca
  - vtk
  - pyqt
  - pandas
  - eigen
  - casadi
  - rbdl
  - packaging
  - pytest
  - setuptools
